# Generated by Django 4.1.7 on 2023-07-24 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarrierName', models.CharField(max_length=35)),
                ('CarrierCode', models.CharField(max_length=3, null=True)),
                ('CarrierAbrv', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PseudoCID', models.CharField(max_length=10)),
                ('Client_Description', models.CharField(max_length=60)),
                ('Client_Code', models.CharField(max_length=8)),
                ('PubCode', models.CharField(blank=True, max_length=4)),
                ('Sales_Type', models.CharField(max_length=1)),
                ('VoiceMail', models.CharField(max_length=4)),
                ('InBnd_TranNo', models.CharField(max_length=10)),
                ('Carrier', models.CharField(max_length=30)),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('INACTIVE', 'In-Active')], default='Pending', max_length=10)),
                ('PR_Date', models.DateField(blank=True, null=True)),
                ('LastUse_Date', models.DateField(blank=True, default='', null=True)),
                ('DID_CNT', models.IntegerField(blank=True, default=0, null=True)),
                ('LeadFileID', models.CharField(blank=True, max_length=30, null=True)),
                ('Notes', models.CharField(blank=True, default='', max_length=60, null=True)),
            ],
            options={
                'db_table': 'ClientInfo',
            },
        ),
        migrations.CreateModel(
            name='ClientPseudoCID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PseudoCID', models.CharField(max_length=10)),
                ('PhoneNo', models.CharField(max_length=10)),
                ('PhnNo_Loc', models.CharField(max_length=2)),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('INACTIVE', 'In-Active')], default='Pending', max_length=10)),
                ('LeadFileID', models.CharField(max_length=30, null=True)),
                ('Deact_Date', models.DateField(blank=True, default=None, null=True)),
                ('client_info', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_pseudocids', to='didmenusystem.clientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='NewClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Description', models.CharField(max_length=60)),
                ('Sales_Type', models.CharField(max_length=1)),
                ('Client_Code', models.CharField(max_length=8)),
                ('PubCode', models.CharField(blank=True, max_length=4)),
                ('InBnd_TranNo', models.CharField(max_length=10)),
                ('VoiceMail', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewOrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeadFileID', models.CharField(max_length=30, null=True)),
                ('Carrier', models.CharField(max_length=30)),
                ('Total_DID_CNT', models.IntegerField(blank=True, default=0, null=True)),
                ('Sel_States', models.CharField(max_length=160)),
                ('PR_Date', models.DateField(blank=True)),
                ('FileName', models.CharField(blank=True, max_length=25)),
                ('OrderComplete', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('P', 'Pending')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='NewPseudoCID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PseudoCID', models.CharField(max_length=10)),
                ('Sales_Type', models.CharField(max_length=1)),
                ('Carrier', models.CharField(max_length=30)),
                ('Status', models.CharField(choices=[('A', 'ACTIVE'), ('I', 'INACTIVE'), ('X', 'UNASSIGNED')], default='I', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNo', models.CharField(max_length=10)),
                ('PseudoCID', models.CharField(max_length=10)),
                ('TFN_PrimaryNo', models.CharField(max_length=3)),
                ('DID_Location', models.CharField(max_length=3, null=True)),
                ('Sales_Type', models.CharField(max_length=1)),
                ('PubCode', models.CharField(max_length=4)),
                ('ClientCode', models.CharField(max_length=8)),
                ('Client_Description', models.CharField(max_length=60)),
                ('VoiceMail', models.CharField(max_length=4)),
                ('Carrier', models.CharField(max_length=30)),
                ('PR_status', models.CharField(max_length=1)),
                ('PR_Date', models.CharField(max_length=10)),
                ('LastUse_Date', models.CharField(max_length=10)),
                ('Notes', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StateName', models.CharField(max_length=50)),
                ('StateAbrv', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PseudoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PseudoCID', models.CharField(max_length=10)),
                ('PhoneNo', models.CharField(max_length=10)),
                ('PhnNo_Loc', models.CharField(blank=True, max_length=2)),
                ('Client_Code', models.CharField(max_length=8)),
                ('InBnd_TranNo', models.CharField(max_length=10)),
                ('Action', models.CharField(choices=[('ADD', 'Add'), ('UPDATE', 'Update'), ('DEACTIVATE', 'Deactivate'), ('ACTIVATE', 'Activate'), ('DELETE', 'Delete')], default='DELETE', max_length=11)),
                ('LeadFileID', models.CharField(max_length=30, null=True)),
                ('FileName', models.CharField(blank=True, max_length=25)),
                ('Carrier', models.CharField(blank=True, max_length=30)),
                ('Deact_Date', models.DateField(blank=True, default='', null=True)),
                ('OkToArchive', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('client_pseudocid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pseudo_files', to='didmenusystem.clientpseudocid')),
            ],
        ),
        migrations.CreateModel(
            name='NewOrderPseudoCID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeadFileID', models.CharField(max_length=30, null=True)),
                ('PseudoCID', models.CharField(max_length=10)),
                ('Client_Description', models.CharField(max_length=60)),
                ('Sales_Type', models.CharField(max_length=1, null=True)),
                ('Client_Code', models.CharField(max_length=8, null=True)),
                ('PubCode', models.CharField(blank=True, max_length=4)),
                ('InBnd_TranNo', models.CharField(max_length=10, null=True)),
                ('VoiceMail', models.CharField(max_length=4, null=True)),
                ('DID_CNT', models.IntegerField(blank=True, default=0, null=True)),
                ('order_info', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pseudo_cids', to='didmenusystem.neworderinfo')),
            ],
        ),
    ]
