# Generated by Django 4.1.7 on 2023-03-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonerecord',
            name='created_at',
        ),
    ]
