# Generated by Django 4.1.7 on 2023-07-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0002_clientlist_clientlistdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlistdata',
            name='PseudoCID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='didmenusystem.clientlist'),
        ),
    ]
