# Generated by Django 4.1.7 on 2023-03-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0002_remove_phonerecord_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonerecord',
            name='Notes',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
