# Generated by Django 4.1.7 on 2023-03-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0003_alter_phonerecord_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonerecord',
            name='DID_Location',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
