# Generated by Django 4.1.7 on 2023-03-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0004_alter_phonerecord_did_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StateName', models.CharField(max_length=50)),
                ('StateAbrv', models.CharField(max_length=2)),
            ],
        ),
    ]
