# Generated by Django 4.1.7 on 2023-03-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0005_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='StateAbrv',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
