# Generated by Django 4.1.7 on 2023-03-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0006_alter_states_stateabrv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarrierName', models.CharField(max_length=35)),
                ('CarrierCode', models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
