# Generated by Django 4.1.7 on 2023-04-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0007_carrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PseudoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PseudoCID', models.CharField(max_length=10)),
                ('PhoneNo', models.CharField(max_length=10)),
                ('ClientCode', models.CharField(max_length=8)),
                ('PrimaryNo', models.CharField(max_length=10)),
                ('PR_Date', models.CharField(max_length=10)),
            ],
        ),
    ]
