# Generated by Django 4.1.7 on 2023-08-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0008_alter_clientlist_pseudocid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlist',
            name='LastUse_Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
