# Generated by Django 4.1.7 on 2023-04-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0008_pseudofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pseudofile',
            name='Action',
            field=models.CharField(choices=[('ADD', 'Add'), ('UPDATE', 'Update'), ('DEACTIVATE', 'Deactivate'), ('ACTIVATE', 'Activate'), ('DELETE', 'Delete')], default='DELETE', max_length=11),
        ),
    ]
