# Generated by Django 4.1.7 on 2023-04-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0009_pseudofile_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PseudoCID', models.CharField(max_length=10)),
                ('Client_Description', models.CharField(max_length=60)),
                ('ClientCode', models.CharField(max_length=8)),
                ('PubCode', models.CharField(max_length=4)),
                ('Sales_Type', models.CharField(max_length=1)),
                ('VoiceMail', models.CharField(max_length=4)),
                ('InBnd_TFN', models.CharField(max_length=10)),
                ('Carrier', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=1)),
                ('PR_Date', models.DateField(blank=True)),
                ('LastUse_Date', models.DateField(blank=True)),
                ('DID_CNT', models.IntegerField(blank=True, default=0, null=True)),
                ('Notes', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPseudoCID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PseudoCID', models.CharField(max_length=10)),
                ('PhoneNo', models.CharField(max_length=10)),
                ('DID_Location', models.CharField(max_length=2)),
                ('Status', models.CharField(max_length=1)),
                ('Deact_Date', models.DateField(blank=True)),
            ],
        ),
    ]
