# Generated by Django 4.1.7 on 2023-04-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0010_clientinfo_clientpseudocid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientinfo',
            old_name='ClientCode',
            new_name='Client_Code',
        ),
        migrations.RenameField(
            model_name='clientinfo',
            old_name='InBnd_TFN',
            new_name='InBnd_TranNo',
        ),
        migrations.RenameField(
            model_name='clientpseudocid',
            old_name='DID_Location',
            new_name='PhnNo_Loc',
        ),
        migrations.RenameField(
            model_name='pseudofile',
            old_name='ClientCode',
            new_name='Client_Code',
        ),
        migrations.RenameField(
            model_name='pseudofile',
            old_name='PR_Date',
            new_name='Deact_Date',
        ),
        migrations.RenameField(
            model_name='pseudofile',
            old_name='PrimaryNo',
            new_name='InBnd_TranNo',
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='LeadFileID',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='clientpseudocid',
            name='LeadFileID',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pseudofile',
            name='LeadFileID',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='Notes',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='PubCode',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
