# Generated by Django 4.1.7 on 2023-08-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0010_neworderlist_neworderlistdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworderlist',
            name='PR_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
