# Generated by Django 4.1.7 on 2023-04-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0011_rename_clientcode_clientinfo_client_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pseudofile',
            name='Deact_Date',
            field=models.DateField(blank=True),
        ),
    ]
