# Generated by Django 4.1.7 on 2023-08-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0011_alter_neworderlist_pr_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPIClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Description', models.CharField(max_length=60)),
                ('Sales_Type', models.CharField(max_length=1)),
                ('Client_Code', models.CharField(max_length=8)),
                ('PubCode', models.CharField(blank=True, max_length=4)),
                ('InBnd_TranNo', models.CharField(max_length=10)),
                ('VoiceMail', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MPIPseudoCIDs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PseudoCID', models.CharField(max_length=10)),
                ('Sales_Type', models.CharField(max_length=1)),
                ('Carrier', models.CharField(max_length=30)),
                ('Status', models.CharField(choices=[('A', 'ACTIVE'), ('I', 'INACTIVE'), ('X', 'UNASSIGNED')], default='I', max_length=1)),
            ],
        ),
    ]
