# Generated by Django 4.1.7 on 2023-08-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0012_mpiclients_mpipseudocids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pseudofile',
            name='client_pseudocid',
        ),
        migrations.AlterModelTable(
            name='clientinfo',
            table=None,
        ),
    ]
