# Generated by Django 4.1.7 on 2023-04-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0012_alter_pseudofile_deact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pseudofile',
            name='OkToArchive',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
