# Generated by Django 4.1.7 on 2023-04-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0013_pseudofile_oktoarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='LeadFileID',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='Status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('DELETE', 'Delete')], default='PENDING', max_length=7),
        ),
    ]
