# Generated by Django 4.1.7 on 2023-09-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0013_remove_pseudofile_client_pseudocid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneRecord',
        ),
    ]
