# Generated by Django 4.1.7 on 2023-09-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0014_delete_phonerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewClientInfo',
        ),
    ]
