# Generated by Django 4.1.7 on 2023-04-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0014_alter_clientinfo_leadfileid_alter_clientinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='Status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('DELETE', 'Delete')], default='Pending', max_length=7),
        ),
    ]
