# Generated by Django 4.1.7 on 2023-04-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0015_alter_clientinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='Status',
            field=models.CharField(max_length=7),
        ),
    ]
