# Generated by Django 4.1.7 on 2023-09-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0015_delete_newclientinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPseudoCID',
        ),
    ]
