# Generated by Django 4.1.7 on 2023-09-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0016_delete_newpseudocid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewOrderPseudoCID',
        ),
    ]
