# Generated by Django 4.1.7 on 2023-09-11 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0017_delete_neworderpseudocid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewOrderInfo',
        ),
    ]
