# Generated by Django 4.1.7 on 2023-04-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0018_clientpseudocid_client_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='LastUse_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
