# Generated by Django 4.1.7 on 2023-09-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0018_delete_neworderinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientPseudoCID',
        ),
    ]
