# Generated by Django 4.1.7 on 2023-09-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0019_delete_clientpseudocid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientInfo',
        ),
    ]
