# Generated by Django 4.1.7 on 2023-04-06 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0019_alter_clientinfo_lastuse_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientinfo',
            table='ClientInfo',
        ),
    ]
