# Generated by Django 4.1.7 on 2023-04-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0020_alter_clientinfo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeadFileID', models.CharField(max_length=30, null=True)),
                ('Carrier', models.CharField(max_length=30)),
                ('DID_CNT', models.IntegerField(blank=True, default=0, null=True)),
                ('Sel_States', models.CharField(max_length=160)),
                ('PR_Date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewOrderPseudoCID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeadFileID', models.CharField(max_length=30, null=True)),
                ('PseudoCID', models.CharField(max_length=10)),
                ('Client_Description', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='NewPseudoCID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PseudoCID', models.CharField(max_length=10)),
                ('Sales_Type', models.CharField(max_length=1)),
                ('Carrier', models.CharField(max_length=30)),
            ],
        ),
    ]
