# Generated by Django 4.1.7 on 2023-09-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0020_delete_clientinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientListArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PseudoCID', models.CharField(max_length=10)),
                ('Client_Description', models.CharField(max_length=60)),
                ('Client_Code', models.CharField(max_length=8)),
                ('PubCode', models.CharField(blank=True, max_length=4)),
                ('Sales_Type', models.CharField(max_length=1)),
                ('PhoneNo', models.CharField(max_length=10)),
                ('PhnNo_Loc', models.CharField(max_length=2)),
                ('VoiceMail', models.CharField(max_length=4)),
                ('InBnd_TranNo', models.CharField(max_length=10)),
                ('Carrier', models.CharField(max_length=30)),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('INACTIVE', 'In-Active')], default='Pending', max_length=10)),
                ('PR_Date', models.DateField(blank=True, null=True)),
                ('LastUse_Date', models.DateField(blank=True, default=None, null=True)),
                ('DID_CNT', models.IntegerField(blank=True, default=0, null=True)),
                ('LeadFileID', models.CharField(max_length=30, null=True)),
                ('Deact_Date', models.DateField(blank=True, default='', null=True)),
                ('Notes', models.CharField(blank=True, default='', max_length=60, null=True)),
            ],
        ),
    ]
