# Generated by Django 4.1.7 on 2023-04-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0021_neworderinfo_neworderpseudocid_newpseudocid'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='CarrierAbrv',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
