# Generated by Django 4.1.7 on 2023-04-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0022_carrier_carrierabrv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='CarrierAbrv',
            field=models.CharField(max_length=3),
        ),
    ]
