# Generated by Django 4.1.7 on 2023-04-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0023_alter_carrier_carrierabrv'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworderinfo',
            name='FileName',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
