# Generated by Django 4.1.7 on 2023-04-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0024_neworderinfo_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Description', models.CharField(max_length=60)),
                ('Sales_Type', models.CharField(max_length=1)),
                ('Client_Code', models.CharField(max_length=8)),
                ('PubCode', models.CharField(blank=True, max_length=4)),
                ('InBnd_TranNo', models.CharField(max_length=10)),
            ],
        ),
    ]
