# Generated by Django 4.1.7 on 2023-04-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0026_neworderpseudocid_order_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworderinfo',
            name='OrderComplete',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
