# Generated by Django 4.1.7 on 2023-04-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0027_neworderinfo_ordercomplete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neworderinfo',
            old_name='DID_CNT',
            new_name='Total_DID_CNT',
        ),
        migrations.AddField(
            model_name='neworderpseudocid',
            name='DID_CNT',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
