# Generated by Django 4.1.7 on 2023-04-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0028_rename_did_cnt_neworderinfo_total_did_cnt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworderinfo',
            name='OrderComplete',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
