# Generated by Django 4.1.7 on 2023-05-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0029_alter_neworderinfo_ordercomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworderpseudocid',
            name='Client_Code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='neworderpseudocid',
            name='InBnd_TranNo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='neworderpseudocid',
            name='PubCode',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='neworderpseudocid',
            name='Sales_Type',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
