# Generated by Django 4.1.7 on 2023-05-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0030_neworderpseudocid_client_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworderinfo',
            name='FileName',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
