# Generated by Django 4.1.7 on 2023-05-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0031_alter_neworderinfo_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='newclientinfo',
            name='VoiceMail',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='neworderpseudocid',
            name='VoiceMail',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
