# Generated by Django 4.1.7 on 2023-05-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0032_newclientinfo_voicemail_neworderpseudocid_voicemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='PR_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientpseudocid',
            name='Deact_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
