# Generated by Django 4.1.7 on 2023-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0033_alter_clientinfo_pr_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='LastUse_Date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='Notes',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='clientpseudocid',
            name='Deact_Date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
