# Generated by Django 4.1.7 on 2023-05-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0034_alter_clientinfo_lastuse_date_alter_clientinfo_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpseudocid',
            name='Status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('DELETE', 'Delete')], default='Pending', max_length=7),
        ),
    ]
