# Generated by Django 4.1.7 on 2023-05-12 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0035_alter_clientpseudocid_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientinfo',
            unique_together={('PseudoCID', 'LeadFileID')},
        ),
    ]
