# Generated by Django 4.1.7 on 2023-05-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0036_alter_clientinfo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientinfo',
            unique_together=set(),
        ),
    ]
