# Generated by Django 4.1.7 on 2023-05-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0037_alter_clientinfo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='Status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('INACTIVE', 'In-Active')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientpseudocid',
            name='Status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('INACTIVE', 'In-Active')], default='Pending', max_length=10),
        ),
    ]
