# Generated by Django 4.1.7 on 2023-05-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didmenusystem', '0038_alter_clientinfo_status_alter_clientpseudocid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pseudofile',
            name='FileName',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
